# Generated by Django 5.0.4 on 2024-05-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profile_picture',
            new_name='product_picture',
        ),
    ]
